import { Profile, Project, Achievement, Technology, TimelineItem } from '../types';

export const MOCK_PROFILE: Profile = {
  id: '00000000-0000-0000-0000-000000000001',
  name: 'Ibnu Abi Ad-Dunya',
  role: 'Software Engineer • SMKN 12 Jakarta',
  hero_title: 'BUILDING DIGITAL PRODUCTS WITH CODE & CURIOSITY.',
  hero_description: 'Architecting scalable cloud solutions, performant web applications, and enterprise software solutions with modern software craft.',
  bio: 'Software engineer from SMKN 12 Jakarta passionate about modern web engineering, cloud computing with AWS, enterprise business software, clean architectures, and developer tooling. Juara Harapan 2 LKS SMK Jakarta Utara bidang IT Software Solution for Business.',
  short_bio: 'Software Engineer & LKS IT Software Solution for Business Competitor.',
  email: 'dev@example.com',
  github_url: 'https://github.com/Hiraetha',
  linkedin_url: 'https://linkedin.com',
  instagram_url: 'https://instagram.com',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  location_label: 'Jakarta, Indonesia (GMT+7)',
  availability_status: 'OPEN FOR NEW OPPORTUNITIES',
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-01',
    title: 'Enterprise Cloud Platform API',
    slug: 'enterprise-cloud-platform-api',
    description: 'High-throughput microservices architecture with NestJS, PostgreSQL, and event-driven caching.',
    long_description: 'Engineered a distributed backend service handling millions of monthly requests with strict latency SLAs. Features role-based access control, distributed tracing, automated migrations, and zero-downtime rolling deployments.',
    cover_image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&auto=format&fit=crop&q=80',
    github_url: 'https://github.com/Hiraetha/cloud-platform-api',
    github_repo_name: 'Hiraetha/cloud-platform-api',
    demo_url: 'https://demo.example.com',
    technologies: ['NestJS', 'TypeScript', 'Supabase', 'Git'],
    category: 'Backend',
    featured: true,
    published: true,
    created_at: '2025-10-12T08:00:00.000Z',
  },
  {
    id: 'proj-02',
    title: 'Cross-Platform Mobile FinTech',
    slug: 'cross-platform-mobile-fintech',
    description: 'Real-time financial analytics, biometric security, and transaction engine with React Native and Expo.',
    long_description: 'Designed and developed a seamless cross-platform mobile application supporting instant biometric authentication, interactive budgeting graphs, encrypted local storage, and offline transaction syncing.',
    cover_image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&auto=format&fit=crop&q=80',
    github_url: 'https://github.com/Hiraetha/cross-platform-fintech',
    github_repo_name: 'Hiraetha/cross-platform-fintech',
    demo_url: 'https://demo.example.com',
    technologies: ['React Native', 'Expo', 'TypeScript', 'Tailwind CSS'],
    category: 'Mobile',
    featured: true,
    published: true,
    created_at: '2025-09-20T10:30:00.000Z',
  },
  {
    id: 'proj-03',
    title: 'Interactive Developer Workspace UI',
    slug: 'interactive-developer-workspace-ui',
    description: 'Neo-brutalist web application for live code editing, markdown documentation, and API debugging.',
    long_description: 'Built with React, Tailwind CSS, and Framer Motion. Explores experimental brutalist design paradigms with high-contrast surfaces, snappy tactile feedback, and accessible keyboard-first navigation.',
    cover_image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&auto=format&fit=crop&q=80',
    github_url: 'https://github.com/Hiraetha/PortofolioMe',
    github_repo_name: 'Hiraetha/PortofolioMe',
    demo_url: 'https://demo.example.com',
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Antigravity IDE'],
    category: 'Frontend',
    featured: true,
    published: true,
    created_at: '2025-08-15T14:15:00.000Z',
  },
  {
    id: 'proj-04',
    title: 'Kantin Cermat Dubes — Digital Canteen System',
    slug: 'kantin-cermat-dubes',
    description: 'Sistem otomasi transaksi dan pengolahan data kantin digital sekolah.',
    long_description: 'Aplikasi manajemen dan digitalisasi alur transaksi kantin sekolah (Dubes / SMKN 12 Jakarta) dengan sistem rekapitulasi data pesanan, pengelolaan stok, dan pencatatan transaksi yang efisien.',
    cover_image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80',
    github_url: 'https://github.com/Hiraetha/Kantin-Cermat-Dubes',
    github_repo_name: 'Hiraetha/Kantin-Cermat-Dubes',
    demo_url: 'https://github.com/Hiraetha/Kantin-Cermat-Dubes',
    technologies: ['PHP', 'Laravel', 'Bootstrap', 'Git'],
    category: 'Backend',
    featured: true,
    published: true,
    created_at: '2025-06-04T12:00:00.000Z',
  }
];

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-00',
    title: 'Juara Harapan 2 — LKS IT Software Solution for Business',
    description: 'Juara Harapan 2 ajang Lomba Kompetensi Siswa (LKS) SMK Wilayah I Jakarta Utara (No: 05/SK-245/2026/LKS-SMK) mewakili SMKN 12 Jakarta. Kompetisi rekayasa solusi perangkat lunak bisnis enterprise, arsitektur database, dan implementasi aplikasi.',
    issuer: 'Sudin Pendidikan Wilayah I Jakarta Utara',
    date: '2026-04-23',
    image_url: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&auto=format&fit=crop&q=80',
    certificate_url: 'https://disdik.jakarta.go.id',
    featured: true,
    created_at: '2026-04-23T00:00:00.000Z',
  },
  {
    id: 'ach-01',
    title: 'Belajar Membuat Front-End Web untuk Pemula',
    description: 'Sertifikasi kompetensi Front-End Web standar industri (45 Jam). Penguasaan manipulasi BOM & DOM dengan JavaScript, interaktivitas event handling, dan persistensi data dengan Web Storage API.',
    issuer: 'Dicoding Indonesia',
    date: '2026-02-23',
    image_url: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop&q=80',
    certificate_url: 'https://dicoding.com/certificates/MRZMWK04RPYQ',
    featured: true,
    created_at: '2026-02-23T00:00:00.000Z',
  },
  {
    id: 'ach-02',
    title: 'Belajar Dasar Pemrograman Web',
    description: 'Fondasi pembuatan website modern (41 Jam). Disusun bersama Google Developers Authorized Training Partner meliputi Semantic HTML5, styling CSS3 mendalam, Box Model, dan Responsive Layout dengan CSS Flexbox.',
    issuer: 'Dicoding x Google Developers Partner',
    date: '2026-01-28',
    image_url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80',
    certificate_url: 'https://dicoding.com/certificates/ERZR2RMEQPYV',
    featured: true,
    created_at: '2026-01-28T00:00:00.000Z',
  },
  {
    id: 'ach-03',
    title: 'Belajar Dasar Cloud dan Gen AI di AWS',
    description: 'Standar kompetensi internasional Amazon Web Services (13 Jam). Pemahaman infrastruktur global AWS, Amazon EC2, S3, DynamoDB, IAM Security, Well-Architected Framework, dan eksplorasi Generative AI.',
    issuer: 'Dicoding Indonesia x AWS',
    date: '2026-01-18',
    image_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    certificate_url: 'https://dicoding.com/certificates/2VX35DKO3PYQ',
    featured: true,
    created_at: '2026-01-18T00:00:00.000Z',
  },
  {
    id: 'ach-04',
    title: 'Memulai Dasar Pemrograman untuk Menjadi Pengembang Software',
    description: 'Standar okupasi Pengembang Software KBJI 2512.03. Lulus dengan Nilai Sempurna 100/100 (Ujian Akhir & Kelulusan Kelas). Menguasai logika pemrograman, flowchart sistem, JavaScript ES6, dan dokumentasi software.',
    issuer: 'Dicoding Indonesia (Kartu Prakerja)',
    date: '2026-01-11',
    image_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80',
    certificate_url: 'https://dicoding.com/certificates/72ZDKNDEVPYW',
    featured: true,
    created_at: '2026-01-11T00:00:00.000Z',
  },
  {
    id: 'ach-05',
    title: 'Sertifikat Uji Kemahiran Berbahasa Indonesia (UKBI)',
    description: 'Uji kemahiran resmi Badan Pengembangan dan Pembinaan Bahasa Kemdikbudristek RI (No: SD-BB-0481420). Meraih Peringkat Semenjana (Skor 446) dengan skor Mendengarkan 530, Membaca 440, dan Merespons Kaidah 368.',
    issuer: 'Kemdikbudristek RI',
    date: '2023-10-14',
    image_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800&auto=format&fit=crop&q=80',
    certificate_url: 'https://ukbi.kemdikbud.go.id',
    featured: false,
    created_at: '2023-10-14T00:00:00.000Z',
  }
];

export const MOCK_TECHNOLOGIES: Technology[] = [
  // Frontend
  { id: 'tech-1', name: 'React', category: 'Frontend', icon: 'Code', description: 'Component-driven UI engineering' },
  { id: 'tech-2', name: 'TypeScript', category: 'Frontend', icon: 'FileCode', description: 'Type safety and enterprise architecture' },
  { id: 'tech-3', name: 'Tailwind CSS', category: 'Frontend', icon: 'Palette', description: 'Utility-first modern styling' },
  { id: 'tech-4', name: 'HTML', category: 'Frontend', icon: 'Globe', description: 'Semantic, accessible web markup' },
  { id: 'tech-5', name: 'Bootstrap', category: 'Frontend', icon: 'Layout', description: 'Rapid responsive prototyping' },

  // Mobile
  { id: 'tech-6', name: 'React Native', category: 'Mobile', icon: 'Smartphone', description: 'Cross-platform native iOS & Android' },
  { id: 'tech-7', name: 'Expo', category: 'Mobile', icon: 'Boxes', description: 'Modern tooling & managed workflow' },

  // Backend
  { id: 'tech-8', name: 'NestJS', category: 'Backend', icon: 'Server', description: 'Enterprise TypeScript backend framework' },
  { id: 'tech-9', name: 'Laravel', category: 'Backend', icon: 'Flame', description: 'Full-featured PHP framework' },
  { id: 'tech-10', name: 'PHP', category: 'Backend', icon: 'Cpu', description: 'Modern web scripting engine' },

  // Tools / Other (Antigravity IDE is explicitly categorized as Tool/Other)
  { id: 'tech-11', name: 'Antigravity IDE', category: 'Tools / Other', icon: 'Terminal', description: 'Agentic developer workflow and AI coding tooling' },
  { id: 'tech-12', name: 'Git', category: 'Tools / Other', icon: 'GitBranch', description: 'Distributed version control system' },
  { id: 'tech-13', name: 'GitHub', category: 'Tools / Other', icon: 'Github', description: 'Collaborative repository hosting and CI/CD' },
  { id: 'tech-14', name: 'Supabase', category: 'Tools / Other', icon: 'Database', description: 'PostgreSQL, Authentication & Storage BaaS' },
  { id: 'tech-15', name: 'Vercel', category: 'Tools / Other', icon: 'Cloud', description: 'Global edge deployments & hosting' }
];

export const MOCK_TIMELINE: TimelineItem[] = [
  {
    id: 'time-0',
    title: 'Juara Harapan 2 LKS SMK — IT Software Solution for Business',
    description: 'Mewakili SMKN 12 Jakarta dalam ajang bergengsi Lomba Kompetensi Siswa (LKS) SMK Tingkat Wilayah I Jakarta Utara bidang IT Software Solution for Business. Berhasil meraih Juara Harapan 2 dalam rekayasa solusi perangkat lunak bisnis terintegrasi.',
    type: 'Competition',
    date: 'April 2026',
  },
  {
    id: 'time-1',
    title: 'Front-End Web Development & Storage Persistence',
    description: 'Menyelesaikan 45 jam kurikulum industri Front-End Web di Dicoding. Menguasai manipulasi DOM dinamis, arsitektur event listener, dan penyimpanan data lokal menggunakan Web Storage API (LocalStorage).',
    type: 'Learning',
    date: 'Februari 2026',
  },
  {
    id: 'time-2',
    title: 'Modern Responsive Web Design (Google Developers Partner)',
    description: 'Menyelesaikan 41 jam pelatihan bersertifikasi Google Developers Authorized Training Partner. Menguasai struktur semantik HTML5, CSS Flexbox modern, dan penyusunan tata letak website responsif lintas platform.',
    type: 'Learning',
    date: 'Januari 2026',
  },
  {
    id: 'time-3',
    title: 'AWS Cloud Computing Infrastructure & Generative AI',
    description: 'Memperdalam arsitektur cloud global dengan kurikulum resmi AWS (13 jam). Menguasai Amazon EC2, VPC, penyimpanan S3/DynamoDB, AWS Well-Architected Framework, dan integrasi Generative AI.',
    type: 'Learning',
    date: 'Januari 2026',
  },
  {
    id: 'time-4',
    title: 'Software Engineering Foundations (Perfect Score 100/100)',
    description: 'Meraih skor sempurna 100/100 pada ujian akhir dan kelulusan program standar okupasi pengembang software KBJI: 2512.03. Menguasai algoritma, logika pemrograman, dasar JavaScript ES6, dan dokumentasi teknis.',
    type: 'Achievement',
    date: 'Januari 2026',
  },
  {
    id: 'time-5',
    title: 'Uji Kemahiran Berbahasa Indonesia (UKBI) — Kemdikbudristek',
    description: 'Mengikuti uji kemahiran berbahasa Indonesia resmi di TUKBI Pusat Jakarta oleh Badan Pengembangan dan Pembinaan Bahasa Kemdikbudristek RI, meraih predikat Semenjana (Skor 446). Menjadi landasan komunikasi profesional dan penulisan dokumentasi.',
    type: 'Achievement',
    date: 'Oktober 2023',
  }
];
